export const DIAL_CODE_PREFIX = '+'
export const DEFAULT_COUNTRY_CODE = 'vn'
export const DEFAULT_DIAL_CODE = '84'
export const DEFAULT_COUNTRY_FIELD_NAME = 'country'
export const DEFAULT_PHONE_FIELD_NAME = 'phone'
